// Fuente común de partidos para Quinielas, Quiniela General y Partidos.
// Generado desde MatchRepository(3).kt.
// Nota: se conserva el mismo orden del repositorio Android; firebaseDocId M01..M72 corresponde al índice del arreglo.
const MATCHES = [
  {
    id: "A1",
    firebaseDocId: "M01",
    group: "Grupo A",
    date: "2026-06-11",
    time: "13:00",
    homeTeam: "México",
    homeFlag: "🇲🇽",
    awayTeam: "Sudáfrica",
    awayFlag: "🇿🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "A2",
    firebaseDocId: "M02",
    group: "Grupo A",
    date: "2026-06-11",
    time: "20:00",
    homeTeam: "Corea del Sur",
    homeFlag: "🇰🇷",
    awayTeam: "República Checa",
    awayFlag: "🇨🇿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "A3",
    firebaseDocId: "M03",
    group: "Grupo A",
    date: "2026-06-18",
    time: "10:00",
    homeTeam: "República Checa",
    homeFlag: "🇨🇿",
    awayTeam: "Sudáfrica",
    awayFlag: "🇿🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "A4",
    firebaseDocId: "M04",
    group: "Grupo A",
    date: "2026-06-18",
    time: "19:00",
    homeTeam: "México",
    homeFlag: "🇲🇽",
    awayTeam: "Corea del Sur",
    awayFlag: "🇰🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "A5",
    firebaseDocId: "M05",
    group: "Grupo A",
    date: "2026-06-24",
    time: "19:00",
    homeTeam: "República Checa",
    homeFlag: "🇨🇿",
    awayTeam: "México",
    awayFlag: "🇲🇽",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "A6",
    firebaseDocId: "M06",
    group: "Grupo A",
    date: "2026-06-24",
    time: "19:00",
    homeTeam: "Sudáfrica",
    homeFlag: "🇿🇦",
    awayTeam: "Corea del Sur",
    awayFlag: "🇰🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "B1",
    firebaseDocId: "M07",
    group: "Grupo B",
    date: "2026-06-12",
    time: "13:00",
    homeTeam: "Canadá",
    homeFlag: "🇨🇦",
    awayTeam: "Bosnia y Herzegovina",
    awayFlag: "🇧🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "B2",
    firebaseDocId: "M08",
    group: "Grupo B",
    date: "2026-06-13",
    time: "13:00",
    homeTeam: "Qatar",
    homeFlag: "🇶🇦",
    awayTeam: "Suiza",
    awayFlag: "🇨🇭",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "B3",
    firebaseDocId: "M09",
    group: "Grupo B",
    date: "2026-06-18",
    time: "13:00",
    homeTeam: "Suiza",
    homeFlag: "🇨🇭",
    awayTeam: "Bosnia y Herzegovina",
    awayFlag: "🇧🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "B4",
    firebaseDocId: "M10",
    group: "Grupo B",
    date: "2026-06-18",
    time: "16:00",
    homeTeam: "Canadá",
    homeFlag: "🇨🇦",
    awayTeam: "Qatar",
    awayFlag: "🇶🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "B5",
    firebaseDocId: "M11",
    group: "Grupo B",
    date: "2026-06-24",
    time: "13:00",
    homeTeam: "Suiza",
    homeFlag: "🇨🇭",
    awayTeam: "Canadá",
    awayFlag: "🇨🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "B6",
    firebaseDocId: "M12",
    group: "Grupo B",
    date: "2026-06-24",
    time: "13:00",
    homeTeam: "Bosnia y Herzegovina",
    homeFlag: "🇧🇦",
    awayTeam: "Qatar",
    awayFlag: "🇶🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "C1",
    firebaseDocId: "M13",
    group: "Grupo C",
    date: "2026-06-13",
    time: "16:00",
    homeTeam: "Brasil",
    homeFlag: "🇧🇷",
    awayTeam: "Marruecos",
    awayFlag: "🇲🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "C2",
    firebaseDocId: "M14",
    group: "Grupo C",
    date: "2026-06-13",
    time: "19:00",
    homeTeam: "Haití",
    homeFlag: "🇭🇹",
    awayTeam: "Escocia",
    awayFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "C3",
    firebaseDocId: "M15",
    group: "Grupo C",
    date: "2026-06-19",
    time: "16:00",
    homeTeam: "Escocia",
    homeFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    awayTeam: "Marruecos",
    awayFlag: "🇲🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "C4",
    firebaseDocId: "M16",
    group: "Grupo C",
    date: "2026-06-19",
    time: "18:30",
    homeTeam: "Brasil",
    homeFlag: "🇧🇷",
    awayTeam: "Haití",
    awayFlag: "🇭🇹",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "C5",
    firebaseDocId: "M17",
    group: "Grupo C",
    date: "2026-06-24",
    time: "16:00",
    homeTeam: "Escocia",
    homeFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    awayTeam: "Brasil",
    awayFlag: "🇧🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "C6",
    firebaseDocId: "M18",
    group: "Grupo C",
    date: "2026-06-24",
    time: "16:00",
    homeTeam: "Marruecos",
    homeFlag: "🇲🇦",
    awayTeam: "Haití",
    awayFlag: "🇭🇹",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "D1",
    firebaseDocId: "M19",
    group: "Grupo D",
    date: "2026-06-12",
    time: "19:00",
    homeTeam: "Estados Unidos",
    homeFlag: "🇺🇸",
    awayTeam: "Paraguay",
    awayFlag: "🇵🇾",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "D2",
    firebaseDocId: "M20",
    group: "Grupo D",
    date: "2026-06-13",
    time: "22:00",
    homeTeam: "Australia",
    homeFlag: "🇦🇺",
    awayTeam: "Turquía",
    awayFlag: "🇹🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "D3",
    firebaseDocId: "M21",
    group: "Grupo D",
    date: "2026-06-25",
    time: "20:00",
    homeTeam: "Turquía",
    homeFlag: "🇹🇷",
    awayTeam: "Estados Unidos",
    awayFlag: "🇺🇸",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "D4",
    firebaseDocId: "M22",
    group: "Grupo D",
    date: "2026-06-25",
    time: "20:00",
    homeTeam: "Paraguay",
    homeFlag: "🇵🇾",
    awayTeam: "Australia",
    awayFlag: "🇦🇺",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "D5",
    firebaseDocId: "M23",
    group: "Grupo D",
    date: "2026-06-19",
    time: "13:00",
    homeTeam: "Estados Unidos",
    homeFlag: "🇺🇸",
    awayTeam: "Australia",
    awayFlag: "🇦🇺",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "D6",
    firebaseDocId: "M24",
    group: "Grupo D",
    date: "2026-06-19",
    time: "21:00",
    homeTeam: "Turquía",
    homeFlag: "🇹🇷",
    awayTeam: "Paraguay",
    awayFlag: "🇵🇾",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "E1",
    firebaseDocId: "M25",
    group: "Grupo E",
    date: "2026-06-14",
    time: "11:00",
    homeTeam: "Alemania",
    homeFlag: "🇩🇪",
    awayTeam: "Curazao",
    awayFlag: "🇨🇼",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "E2",
    firebaseDocId: "M26",
    group: "Grupo E",
    date: "2026-06-14",
    time: "17:00",
    homeTeam: "Costa de Marfil",
    homeFlag: "🇨🇮",
    awayTeam: "Ecuador",
    awayFlag: "🇪🇨",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "E3",
    firebaseDocId: "M27",
    group: "Grupo E",
    date: "2026-06-20",
    time: "14:00",
    homeTeam: "Alemania",
    homeFlag: "🇩🇪",
    awayTeam: "Costa de Marfil",
    awayFlag: "🇨🇮",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "E4",
    firebaseDocId: "M28",
    group: "Grupo E",
    date: "2026-06-20",
    time: "18:00",
    homeTeam: "Ecuador",
    homeFlag: "🇪🇨",
    awayTeam: "Curazao",
    awayFlag: "🇨🇼",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "E5",
    firebaseDocId: "M29",
    group: "Grupo E",
    date: "2026-06-25",
    time: "14:00",
    homeTeam: "Curazao",
    homeFlag: "🇨🇼",
    awayTeam: "Costa de Marfil",
    awayFlag: "🇨🇮",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "E6",
    firebaseDocId: "M30",
    group: "Grupo E",
    date: "2026-06-25",
    time: "14:00",
    homeTeam: "Ecuador",
    homeFlag: "🇪🇨",
    awayTeam: "Alemania",
    awayFlag: "🇩🇪",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "F1",
    firebaseDocId: "M31",
    group: "Grupo F",
    date: "2026-06-14",
    time: "20:00",
    homeTeam: "Suecia",
    homeFlag: "🇸🇪",
    awayTeam: "Túnez",
    awayFlag: "🇹🇳",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "F2",
    firebaseDocId: "M32",
    group: "Grupo F",
    date: "2026-06-14",
    time: "14:00",
    homeTeam: "Países Bajos",
    homeFlag: "🇳🇱",
    awayTeam: "Japón",
    awayFlag: "🇯🇵",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "F3",
    firebaseDocId: "M33",
    group: "Grupo F",
    date: "2026-06-20",
    time: "11:00",
    homeTeam: "Países Bajos",
    homeFlag: "🇳🇱",
    awayTeam: "Suecia",
    awayFlag: "🇸🇪",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "F4",
    firebaseDocId: "M34",
    group: "Grupo F",
    date: "2026-06-20",
    time: "22:00",
    homeTeam: "Túnez",
    homeFlag: "🇹🇳",
    awayTeam: "Japón",
    awayFlag: "🇯🇵",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "F5",
    firebaseDocId: "M35",
    group: "Grupo F",
    date: "2026-06-25",
    time: "17:00",
    homeTeam: "Japón",
    homeFlag: "🇯🇵",
    awayTeam: "Suecia",
    awayFlag: "🇸🇪",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "F6",
    firebaseDocId: "M36",
    group: "Grupo F",
    date: "2026-06-25",
    time: "17:00",
    homeTeam: "Túnez",
    homeFlag: "🇹🇳",
    awayTeam: "Países Bajos",
    awayFlag: "🇳🇱",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "G1",
    firebaseDocId: "M37",
    group: "Grupo G",
    date: "2026-06-15",
    time: "13:00",
    homeTeam: "Bélgica",
    homeFlag: "🇧🇪",
    awayTeam: "Egipto",
    awayFlag: "🇪🇬",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "G2",
    firebaseDocId: "M38",
    group: "Grupo G",
    date: "2026-06-15",
    time: "19:00",
    homeTeam: "Irán",
    homeFlag: "🇮🇷",
    awayTeam: "Nueva Zelanda",
    awayFlag: "🇳🇿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "G3",
    firebaseDocId: "M39",
    group: "Grupo G",
    date: "2026-06-21",
    time: "13:00",
    homeTeam: "Bélgica",
    homeFlag: "🇧🇪",
    awayTeam: "Irán",
    awayFlag: "🇮🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "G4",
    firebaseDocId: "M40",
    group: "Grupo G",
    date: "2026-06-21",
    time: "17:00",
    homeTeam: "Nueva Zelanda",
    homeFlag: "🇳🇿",
    awayTeam: "Egipto",
    awayFlag: "🇪🇬",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "G5",
    firebaseDocId: "M41",
    group: "Grupo G",
    date: "2026-06-26",
    time: "21:00",
    homeTeam: "Egipto",
    homeFlag: "🇪🇬",
    awayTeam: "Irán",
    awayFlag: "🇮🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "G6",
    firebaseDocId: "M42",
    group: "Grupo G",
    date: "2026-06-26",
    time: "21:00",
    homeTeam: "Nueva Zelanda",
    homeFlag: "🇳🇿",
    awayTeam: "Bélgica",
    awayFlag: "🇧🇪",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "H1",
    firebaseDocId: "M43",
    group: "Grupo H",
    date: "2026-06-15",
    time: "10:00",
    homeTeam: "España",
    homeFlag: "🇪🇸",
    awayTeam: "Cabo Verde",
    awayFlag: "🇨🇻",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "H2",
    firebaseDocId: "M44",
    group: "Grupo H",
    date: "2026-06-15",
    time: "16:00",
    homeTeam: "Arabia Saudita",
    homeFlag: "🇸🇦",
    awayTeam: "Uruguay",
    awayFlag: "🇺🇾",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "H3",
    firebaseDocId: "M45",
    group: "Grupo H",
    date: "2026-06-21",
    time: "16:00",
    homeTeam: "Uruguay",
    homeFlag: "🇺🇾",
    awayTeam: "Cabo Verde",
    awayFlag: "🇨🇻",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "H4",
    firebaseDocId: "M46",
    group: "Grupo H",
    date: "2026-06-21",
    time: "10:00",
    homeTeam: "España",
    homeFlag: "🇪🇸",
    awayTeam: "Arabia Saudita",
    awayFlag: "🇸🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "H5",
    firebaseDocId: "M47",
    group: "Grupo H",
    date: "2026-06-26",
    time: "18:00",
    homeTeam: "Cabo Verde",
    homeFlag: "🇨🇻",
    awayTeam: "Arabia Saudita",
    awayFlag: "🇸🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "H6",
    firebaseDocId: "M48",
    group: "Grupo H",
    date: "2026-06-26",
    time: "18:00",
    homeTeam: "Uruguay",
    homeFlag: "🇺🇾",
    awayTeam: "España",
    awayFlag: "🇪🇸",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "I1",
    firebaseDocId: "M49",
    group: "Grupo I",
    date: "2026-06-16",
    time: "13:00",
    homeTeam: "Francia",
    homeFlag: "🇫🇷",
    awayTeam: "Senegal",
    awayFlag: "🇸🇳",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "I2",
    firebaseDocId: "M50",
    group: "Grupo I",
    date: "2026-06-16",
    time: "16:00",
    homeTeam: "Irak",
    homeFlag: "🇮🇶",
    awayTeam: "Noruega",
    awayFlag: "🇳🇴",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "I3",
    firebaseDocId: "M51",
    group: "Grupo I",
    date: "2026-06-22",
    time: "18:00",
    homeTeam: "Noruega",
    homeFlag: "🇳🇴",
    awayTeam: "Senegal",
    awayFlag: "🇸🇳",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "I4",
    firebaseDocId: "M52",
    group: "Grupo I",
    date: "2026-06-22",
    time: "15:00",
    homeTeam: "Francia",
    homeFlag: "🇫🇷",
    awayTeam: "Irak",
    awayFlag: "🇮🇶",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "I5",
    firebaseDocId: "M53",
    group: "Grupo I",
    date: "2026-06-26",
    time: "13:00",
    homeTeam: "Noruega",
    homeFlag: "🇳🇴",
    awayTeam: "Francia",
    awayFlag: "🇫🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "I6",
    firebaseDocId: "M54",
    group: "Grupo I",
    date: "2026-06-26",
    time: "13:00",
    homeTeam: "Senegal",
    homeFlag: "🇸🇳",
    awayTeam: "Irak",
    awayFlag: "🇮🇶",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "J1",
    firebaseDocId: "M55",
    group: "Grupo J",
    date: "2026-06-16",
    time: "19:00",
    homeTeam: "Argentina",
    homeFlag: "🇦🇷",
    awayTeam: "Argelia",
    awayFlag: "🇩🇿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "J2",
    firebaseDocId: "M56",
    group: "Grupo J",
    date: "2026-06-16",
    time: "22:00",
    homeTeam: "Austria",
    homeFlag: "🇦🇹",
    awayTeam: "Jordania",
    awayFlag: "🇯🇴",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "J3",
    firebaseDocId: "M57",
    group: "Grupo J",
    date: "2026-06-22",
    time: "11:00",
    homeTeam: "Argentina",
    homeFlag: "🇦🇷",
    awayTeam: "Austria",
    awayFlag: "🇦🇹",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "J4",
    firebaseDocId: "M58",
    group: "Grupo J",
    date: "2026-06-22",
    time: "21:00",
    homeTeam: "Jordania",
    homeFlag: "🇯🇴",
    awayTeam: "Argelia",
    awayFlag: "🇩🇿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "J5",
    firebaseDocId: "M59",
    group: "Grupo J",
    date: "2026-06-27",
    time: "20:00",
    homeTeam: "Jordania",
    homeFlag: "🇯🇴",
    awayTeam: "Argentina",
    awayFlag: "🇦🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "J6",
    firebaseDocId: "M60",
    group: "Grupo J",
    date: "2026-06-27",
    time: "20:00",
    homeTeam: "Argelia",
    homeFlag: "🇩🇿",
    awayTeam: "Austria",
    awayFlag: "🇦🇹",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "K1",
    firebaseDocId: "M61",
    group: "Grupo K",
    date: "2026-06-17",
    time: "11:00",
    homeTeam: "Portugal",
    homeFlag: "🇵🇹",
    awayTeam: "Congo DR",
    awayFlag: "🇨🇩",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "K2",
    firebaseDocId: "M62",
    group: "Grupo K",
    date: "2026-06-17",
    time: "20:00",
    homeTeam: "Uzbekistán",
    homeFlag: "🇺🇿",
    awayTeam: "Colombia",
    awayFlag: "🇨🇴",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "K3",
    firebaseDocId: "M63",
    group: "Grupo K",
    date: "2026-06-23",
    time: "20:00",
    homeTeam: "Colombia",
    homeFlag: "🇨🇴",
    awayTeam: "Congo DR",
    awayFlag: "🇨🇩",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "K4",
    firebaseDocId: "M64",
    group: "Grupo K",
    date: "2026-06-23",
    time: "11:00",
    homeTeam: "Portugal",
    homeFlag: "🇵🇹",
    awayTeam: "Uzbekistán",
    awayFlag: "🇺🇿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "K5",
    firebaseDocId: "M65",
    group: "Grupo K",
    date: "2026-06-27",
    time: "17:30",
    homeTeam: "Colombia",
    homeFlag: "🇨🇴",
    awayTeam: "Portugal",
    awayFlag: "🇵🇹",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "K6",
    firebaseDocId: "M66",
    group: "Grupo K",
    date: "2026-06-27",
    time: "17:30",
    homeTeam: "Congo DR",
    homeFlag: "🇨🇩",
    awayTeam: "Uzbekistán",
    awayFlag: "🇺🇿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "L1",
    firebaseDocId: "M67",
    group: "Grupo L",
    date: "2026-06-17",
    time: "14:00",
    homeTeam: "Inglaterra",
    homeFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    awayTeam: "Croacia",
    awayFlag: "🇭🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "L2",
    firebaseDocId: "M68",
    group: "Grupo L",
    date: "2026-06-17",
    time: "17:00",
    homeTeam: "Ghana",
    homeFlag: "🇬🇭",
    awayTeam: "Panamá",
    awayFlag: "🇵🇦",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "L3",
    firebaseDocId: "M69",
    group: "Grupo L",
    date: "2026-06-23",
    time: "14:00",
    homeTeam: "Inglaterra",
    homeFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    awayTeam: "Ghana",
    awayFlag: "🇬🇭",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "L4",
    firebaseDocId: "M70",
    group: "Grupo L",
    date: "2026-06-23",
    time: "17:00",
    homeTeam: "Panamá",
    homeFlag: "🇵🇦",
    awayTeam: "Croacia",
    awayFlag: "🇭🇷",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "L5",
    firebaseDocId: "M71",
    group: "Grupo L",
    date: "2026-06-27",
    time: "15:00",
    homeTeam: "Panamá",
    homeFlag: "🇵🇦",
    awayTeam: "Inglaterra",
    awayFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "L6",
    firebaseDocId: "M72",
    group: "Grupo L",
    date: "2026-06-27",
    time: "15:00",
    homeTeam: "Croacia",
    homeFlag: "🇭🇷",
    awayTeam: "Ghana",
    awayFlag: "🇬🇭",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_1",
    firebaseDocId: "M73",
    group: "16avos de Final",
    date: "2026-06-28",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_2",
    firebaseDocId: "M74",
    group: "16avos de Final",
    date: "2026-06-28",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_3",
    firebaseDocId: "M75",
    group: "16avos de Final",
    date: "2026-06-29",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_4",
    firebaseDocId: "M76",
    group: "16avos de Final",
    date: "2026-06-29",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_5",
    firebaseDocId: "M77",
    group: "16avos de Final",
    date: "2026-06-30",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_6",
    firebaseDocId: "M78",
    group: "16avos de Final",
    date: "2026-06-30",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_7",
    firebaseDocId: "M79",
    group: "16avos de Final",
    date: "2026-07-01",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_8",
    firebaseDocId: "M80",
    group: "16avos de Final",
    date: "2026-07-01",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_9",
    firebaseDocId: "M81",
    group: "16avos de Final",
    date: "2026-07-02",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_10",
    firebaseDocId: "M82",
    group: "16avos de Final",
    date: "2026-07-02",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_11",
    firebaseDocId: "M83",
    group: "16avos de Final",
    date: "2026-07-03",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_12",
    firebaseDocId: "M84",
    group: "16avos de Final",
    date: "2026-07-03",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_13",
    firebaseDocId: "M85",
    group: "16avos de Final",
    date: "2026-07-03",
    time: "20:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_14",
    firebaseDocId: "M86",
    group: "16avos de Final",
    date: "2026-07-04",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_15",
    firebaseDocId: "M87",
    group: "16avos de Final",
    date: "2026-07-04",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R32_16",
    firebaseDocId: "M88",
    group: "16avos de Final",
    date: "2026-07-04",
    time: "20:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_1",
    firebaseDocId: "M89",
    group: "Octavos de Final",
    date: "2026-07-05",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_2",
    firebaseDocId: "M90",
    group: "Octavos de Final",
    date: "2026-07-05",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_3",
    firebaseDocId: "M91",
    group: "Octavos de Final",
    date: "2026-07-06",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_4",
    firebaseDocId: "M92",
    group: "Octavos de Final",
    date: "2026-07-06",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_5",
    firebaseDocId: "M93",
    group: "Octavos de Final",
    date: "2026-07-07",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_6",
    firebaseDocId: "M94",
    group: "Octavos de Final",
    date: "2026-07-07",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_7",
    firebaseDocId: "M95",
    group: "Octavos de Final",
    date: "2026-07-08",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "R16_8",
    firebaseDocId: "M96",
    group: "Octavos de Final",
    date: "2026-07-08",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "QF_1",
    firebaseDocId: "M97",
    group: "Cuartos de Final",
    date: "2026-07-09",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "QF_2",
    firebaseDocId: "M98",
    group: "Cuartos de Final",
    date: "2026-07-09",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "QF_3",
    firebaseDocId: "M99",
    group: "Cuartos de Final",
    date: "2026-07-10",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "QF_4",
    firebaseDocId: "M100",
    group: "Cuartos de Final",
    date: "2026-07-10",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "SF_1",
    firebaseDocId: "M101",
    group: "Semifinales",
    date: "2026-07-14",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "SF_2",
    firebaseDocId: "M102",
    group: "Semifinales",
    date: "2026-07-15",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "3RD",
    firebaseDocId: "M103",
    group: "Tercer Lugar",
    date: "2026-07-18",
    time: "13:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
  {
    id: "FIN",
    firebaseDocId: "M104",
    group: "Final",
    date: "2026-07-19",
    time: "17:00",
    homeTeam: "Por definir",
    homeFlag: "🏳️",
    awayTeam: "Por definir",
    awayFlag: "🏳️",
    realHomeScore: null,
    realAwayScore: null,
    started: false,
    finished: false,
    isActive: false,
  },
];

function getMatchById(id) {
  return MATCHES.find((match) => match.id === id);
}

function groupMatchesByGroup(matches = MATCHES) {
  return matches.reduce((acc, match) => {
    (acc[match.group] ||= []).push(match);
    return acc;
  }, {});
}

function getTeamsFromGroup(groupName, matches = MATCHES) {
  const map = new Map();
  matches
    .filter((match) => match.group === groupName)
    .forEach((match) => {
      map.set(match.homeTeam, match.homeFlag);
      map.set(match.awayTeam, match.awayFlag);
    });
  return [...map.entries()].map(([team, flag]) => ({ team, flag }));
}

export { MATCHES, getMatchById, groupMatchesByGroup, getTeamsFromGroup };
